<Project Sdk="Tomat.Terraria.ModLoader.Sdk/2.1.1">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<TmlVersion>dev</TmlVersion>
		<TmlBuildBootstrapFeatures>tomat.environmentmodlist;tomat.enablemod;lolxd87.splashskip;tomat.assethotreloading</TmlBuildBootstrapFeatures>
	</PropertyGroup>
	
	<ItemGroup>
		<Publicize Include="tModLoader;ReLogic;FNA" IncludeVirtualMembers="false" IncludeCompilerGeneratedMembers="false" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Properties\" />
	</ItemGroup>
	
</Project>